#!/bin/bash

# Easy Login Bash Script into Various OTW Bandit Levels
#########################################################

# Check README.txt for a detailed explanation of how to use it.




# Check if any arguments have been passed
if [ $# -eq 0 ]; then
	echo "Error: No argument passed"
	echo "Usage: $0 <argument>"
	exit 1
fi


BANDIT_URL="bandit.labs.overthewire.org"
BANDIT_LEVEL="bandit$1"


# Check if password file exists
# BANDIT_LEVEL should have the same name as the password file
if [ ! -f "$BANDIT_LEVEL" ]; then
	echo "Error: Password file '$BANDIT_LEVEL' not found"
	echo exit 1
fi


sshpass -f $BANDIT_LEVEL ssh -p 2220 ${BANDIT_LEVEL}@${BANDIT_URL}



